name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Install dependencies
        run: yarn instasll --frazen-lockfile
      - name: Unit Tests
        run: yarn test --watchAll=false
      - name: E2E Tests
        use: cypress-io/github-actions@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
